# Generated by Django 5.0 on 2023-12-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
